import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import Providers from "@/store/provider";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ampere",
  description: "Generated by Abdoulrahman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastContainer theme="colored" position="top-center" />

        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
